/// raum create
###
POST http://localhost:3000/raum/add
Content-Type: application/json

{
  "raumNr": 3,
  "kapazitaet": 2,
  "raumpreis": 10
}

### // Raum list all
GET http://localhost:3000/raum/show

### // Raum show
GET http://localhost:3000/raum/show/5fddfed7e64935575f958fb0

### // Raum delete
DELETE http://localhost:3000/raum/delete/5fdddeb216a2d413d8f0b65e

### // Raum update
PUT  http://localhost:3000/raum/edit/5fddfed7e64935575f958fb0
Content-Type: application/json

{
  "raumNr": 16,
  "kapazitaet": 15,
  "raumpreis": 16
}

### // Raum Verfügbarkeit
POST http://localhost:3000/raum/verfuegbarkeit/5fdf48ac29a2292c321404a7
Content-Type: application/json

{
  "raum": 1,
  "start_datum": "2028-12-31",
  "end_datum": "2029-02-02"
}
