/// raum create
###
POST http://localhost:3000/raum/add
Content-Type: application/json

{
  "raumNr": 3,
  "kapazitaet": 2,
  "raumpreis": 10
}

### // Raum list all
GET http://localhost:3000/raum/list

### // Raum show
GET http://localhost:3000/raum/show/5fddfed7e64935575f958fb0

### // Raum delete
DELETE http://localhost:3000/raum/delete/5fdddeb216a2d413d8f0b65e

### // Raum update
PUT  http://localhost:3000/raum/edit/5fddfed7e64935575f958fb0
Content-Type: application/json

{
  "raumNr": 16,
  "kapazitaet": 15,
  "raumpreis": 16
}

### // Raum Verfügbarkeit
POST http://localhost:3000/raum/verfuegbarkeit/:id
Content-Type: application/json

{
  "startDatum": "2020-12-20",
  "endDatum": "2020-12-20"
}
