/// Teilnehmer registration
###
POST http://localhost:3000/teilnehmer/registration/add
Content-Type: application/json

{
  "name": "meier",
  "vorname": "herbert",
  "email": "herbert@tokentest4.de",
  "password": "test",
  "password2": "test"
}

### // Teilnehmer list all
GET http://localhost:3000/teilnehmer
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlcmJlcnRAbWVpZXIyLmRlIiwidXNlcklEIjoiNWZlMzJlMjg3YzdlOTE1Yzk1MzBjNWNjIiwiaWF0IjoxNjA4OTgxODcxLCJleHAiOjE2MDg5ODU0NzF9.e7Zn4ZUfKuBRmP13KSgdpd_rieL5VXg0ixA-VUB1MAk

### // Teilnehmer show one
GET http://localhost:3000/teilnehmer/showOne/5fe9ce24fc71287e0f249cf1


### // Teilnehmer delete (could be changed to :id as well
DELETE http://localhost:3000/teilnehmer/delete/5fdc8a634098564c24f7de70

### // Teilnehmer update
PUT  http://localhost:3000/teilnehmer/edit/:id
Content-Type: application/json

{
  "name": "Update Teesttter",
  "vorname": "test32123",
  "email": "test666@test.de",
  "passwort": "123456"
}

### // log in
POST http://localhost:3000/teilnehmer/login
Content-Type: application/json

{
  "email": "herbert@tokentest2.de",
  "password": "test"
}

### // log out
DELETE http://localhost:3000/teilnehmer/logout
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlcmJlcnRAdG9rZW50ZXN0Mi5kZSIsInVzZXJJRCI6IjVmZTcxOTEwODQ5OTA3Njk2NjI2YThlMCIsImlhdCI6MTYwODk4MzQ1MywiZXhwIjoxNjA4OTg3MDUzfQ.szleymoDS1Kli1CyZtV_77m0XWzG-fvPNsl5iOEsW3g"
}
