/// add verantstaltung
###
POST http://localhost:3000/veranstaltung/add
Content-Type: application/json

{
  "titel": "Test Event 11",
  "raum": "5fecb38a477f4722004bbdb0",
  "veranstalter": "5fe095001b550c3f060ed989",
  "teilnehmerzahl": 8,
  "start_datum":"2021-02-23",
  "end_datum": "2021-02-25",
  "veranstalter_preis": 400,
  "teilnehmer_preis": 25,
  "sichtbarkeit": true,
  "angebotsstatus": "Angebot akzeptiert"

}

### // Veranstaltung list all
GET http://localhost:3000/veranstaltung/show

### // Veranstaltung show one
GET http://localhost:3000/veranstaltung/show/5fdf45bc456c312bb092086f

### // Veranstaltung delete
DELETE http://localhost:3000/veranstaltung/delete/5fdfb9fced9dea3581f17ff0

### // Veranstaltung update
PUT  http://localhost:3000/veranstaltung/edit/5fde3a848cbb171f87bcb012
Content-Type: application/json

{
  "titel": "geupdateter Titel"

}
###



