/// add verantstaltung
###
POST http://localhost:3000/veranstaltung/add
Content-Type: application/json

{
  "titel": "Test Event 01",

  "teilnehmerzahl": 8,
  "veranstalter_preis": 400,
  "teilnehmer_preis": 25,
  "sichtbarkeit": true,
  "angebotsstatus": "Angebot akzeptiert"

}

### // Veranstaltung list all
GET http://localhost:3000/veranstaltung/show

### // Veranstaltung show one
GET http://localhost:3000/veranstaltung/show/5fde3a848cbb171f87bcb012

### // Veranstaltung delete
DELETE http://localhost:3000/veranstaltung/delete/5fde3b8f8cbb171f87bcb013

### // Veranstaltung update
PUT  http://localhost:3000/veranstaltung/edit/5fde3a848cbb171f87bcb012
Content-Type: application/json

{
  "titel": "geupdateter Titel"

}
###



