/// add verantstaltung
###
POST http://localhost:3000/veranstaltung/add
Content-Type: application/json

{
  "titel": "BugCheck",
  "raum": "44",
  "veranstalter": "frank2@meier2.de",
  "teilnehmerzahl": 8,
  "start_datum":"2021-01-04",
  "end_datum": "2021-01-07",
  "veranstalter_preis": 400,
  "teilnehmer_preis": 25,
  "sichtbarkeit": true,
  "angebotsstatus": "intern"

}

### // Veranstaltung list all
GET http://localhost:3000/veranstaltung/show

### // Veranstaltung show one
GET http://localhost:3000/veranstaltung/showOne/5ff357a5a4cd92651c13ec2e

### // Veranstaltung delete
DELETE http://localhost:3000/veranstaltung/delete/5fdfb9fced9dea3581f17ff0

### // Veranstaltung update
PUT  http://localhost:3000/veranstaltung/edit/5fecee5625f7b034db598063
Content-Type: application/json

{
  "titel": "NeuerTitel",
  "teilnehmerzahl": "10"

}
###
// get Teilnehmerliste pro Veranstaltung
GET http://localhost:3000/veranstaltung/showOne/list/5ff357a5a4cd92651c13ec2e



