/// veranstalter registration
###
POST http://localhost:3000/veranstalter/registration/add
Content-Type: application/json


{
  "name": "meier2",
  "vorname": "frank2",
  "unternehmen": "google",
  "email": "frank2@meier2.de",
  "password": "test",
  "password2": "test"
}

### // veranstalter list all
GET http://localhost:3000/veranstalter/show

### // veranstalter show one
GET http://localhost:3000/veranstalter/showOne
Content-Type: application/json

{
"email": "klaus-fischer96@gmx.de"
}

### // veranstalter delete (could be changed to :id as well
DELETE http://localhost:3000/veranstalter/delete/5fde4e43dea39a2267afa50f

### // veranstalter update
PUT  http://localhost:3000/veranstalter/edit/5fde4ab98f02fd21e64e50f2
Content-Type: application/json

{
  "name": "mueller2",
  "vorname": "bernd",
  "unternehmen": "google",
  "email": "test12345@vms132.de",
  "passwort": "mueller1"
}

### // get

GET http://localhost:3000/veranstalter/get/5fdf842e0a5c7a3039b8810c

### // log in
POST http://localhost:3000/veranstalter/login
Content-Type: application/json

{
  "email": "frank2@meier2.de",
  "password": "test"
}

### // Storno
DELETE http://localhost:3000/veranstalter/storno/5ff7314f5304fba515200a24
